---
- name: Shell command Uptime
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Uptime
      shell: "uptime"
      register: shell_output

    - name: Display Command Output
      debug:
        msg: "{{ shell_output.stdout }}"
