---
- name: Get Uptime Information
  hosts: all
  

  tasks:
    - name: Run Uptime Command
      command: uptime
      register: uptime_output

    - name: Display Uptime Information
      debug:
        var: uptime_output.stdout_lines

